### ISSUE TITLE
Problems loading Talk

### ISSUE THREAD

**Issue by vjbakker** [zooniverse/condors#82]
We are experience difficulty loading Talk. The problem seems to occur during the same time interval each day (in the evening in the US). Rumors are that you know about this already, and it occurs on multiple projects, but it's new to me so I thought I'd report it. More here: http://talk.condorwatch.org/#/boards/BCW0000001/discussions/DCW00003fs?page=1&comment_id=548bc272bb7b560fa8000017

**Comment by astopy** [comment]
This issue should hopefully have been fixed for the last couple of weeks. Could you confirm if you’ve seen this happen recently?

**Comment by vjbakker** [comment]
Yes, seems to be resolved now. Thanks for following up.
    Vickie
    
    Adam McMaster wrote on 2/3/2015 10:33
      AM:
    
    This issue should hopefully have been fixed for the
      last couple of weeks. Could you confirm if you’ve seen this happen
      recently?
      
      
      > On 22 Dec 2014, at 18:43, Chris Lintott
      <notifications@github.com> wrote:
      
      > 
      > Assigned #82
      <https://github.com/zooniverse/condors/issues/82> to @astopy
      <https://github.com/astopy>.
      
      > 
      > —
      
      > Reply to this email directly or view it on GitHub
      <https://github.com/zooniverse/condors/issues/82#event-211034485>.
      
      >
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    
      
      
        
      
          **********************************
          Vickie Bakker
          Assistant research professor
          Department of Ecology
          Montana State University
          Bozeman, MT 59717
          **********************************
