### ISSUE TITLE
Specific subjects need to be selectable by scientsts

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/condors#83]
Such as `condorwatch.org/#/classify/:subject_id`

A couple examples exist in prior projects, such as Radio Galaxy Zoo, Planet Four, and Penguin Watch. Penguins is the best implementation, as it also checks if the current user is a scientists before allowing them to select a subject. Code available at https://github.com/zooniverse/zooniverse-readymade/blob/6cedd/src/classify-page.coffee in the `onActivate`, `isUserScientist`, and `getNextSubject`.

**Comment by srallen** [comment]
This is merged and deployed to production.
