### ISSUE TITLE
Distortions and other new bugs

### ISSUE THREAD

**Issue by vjbakker** [zooniverse/condors#89]
There are several new site issues that have popped up the last few days on CondorWatch. I have experienced some of them. Users are reporting that they are going to wait until they are fixed so hopefully you can take a look.  See recent posts here, and thanks in advance:
http://talk.condorwatch.org/#/boards/BCW0000001/discussions/DCW000046x?page=6&comment_id=556f617d5135d0741e0002dc

**Comment by srallen** [comment]
@vjbakker, this is now fixed. The placeholder image service (placehold.it) changed their service a couple of days ago that affected the rendered images with words in them. I've updated the URL and it's now displaying correctly.
